version: '3.7'
services:


  postgis:
    image: mdillon/postgis:11
    container_name: postgis
    restart: always
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - 5432:5432

  geopetl:
    depends_on:
      - "postgis"
    build:
      context: .
    container_name: geopetl
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_HOST
