version: '3.7'
services:

# Docker-compose for testing postgis geopetl tests against postgresql with postgis

  postgis:
    image: mdillon/postgis:11
    container_name: postgis
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - 5432:5432

  # docker pull point image from ecr
  postgres_sde:
    image: 880708401960.dkr.ecr.us-east-1.amazonaws.com/postgresql-sde:point-registered
    container_name: postgres-sde
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
    ports:
      - 5433:5432

  geopetl:
    depends_on:
      - 'postgis'
    build:
      context: .
      dockerfile: postgis_Dockerfile
    container_name: geopetl
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_HOST
