version: '3.7'
services:

# Docker-compose for testing postgis geopetl tests against postgresql with postgis

  # Postgres database with postgis configured
  postgis:
    image: mdillon/postgis:11
    container_name: postgis
    environment:
      - POSTGRES_USER
      - POSTGRES_PASSWORD
      - POSTGRES_DB
      - POSTGRES_HOST_AUTH_METHOD

  geopetl:
    depends_on:
      - 'postgis'
    build:
      context: .
      dockerfile: geopetl_Dockerfile
    container_name: geopetl
    # Pass connection parameters for both databases to geopetl
    # so our pytest scripts can connect to both.
    environment:
      - POSTGIS_HOST=
      - POSTGIS_USER=
      - POSTGIS_DB=
      - POSTGIS_PASSWORD=
