version: '3.7'
services:

# Docker-compose for testing postgis geopetl tests against postgresql with postgis


  geopetl:
    build:
      context: .
      dockerfile: sde_rds_Dockerfile
    container_name: geopetl
    # Pass connection parameters for both databases to geopetl
    # so our pytest scripts can connect to both.
    environment:
      - PASSWORD=secretpassword
      - HOST=rds-postgis-tester2.cfuoybzycpox.us-east-1.rds.amazonaws.com
      - USER=test_user
      - DB=rds_tester
