# .github/workflows/main.yml
name: CI

# Controls when the action will run. Triggers the workflow on push or pull request events but only for the master branch.
on:
  push:
    branches: add_tests


# A workflow run is made up of one or more jobs that can run sequentially or in parallel

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-16.04

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: print hw
      run: echo Hello, world!

#    # Runs a set of commands using the runners shell
#    - name: Run a multi-line script
#      run: |
#        echo Add other actions to build,
#        echo test, and deploy your project.


    - name: Docker Stuff
      description: build and run image
      env:
        oracle_user: ${{secrets.oracle_user}}
        oracle_pw: ${{secrets.oracle_pw}}
        oracle_host: ${{secrets.oracle_host}}
        oracle_service_name: ${{secrets.oracle_service_name}}
        oracle_port: ${{secrets.oracle_port}}
      inputs:
        oracle_user:
          description: 'user'
          required: false
          default: 'World'
      runs:
        using: 'docker'
        image: 'Dockerfile'
        args:
          - ${{ $oracle_user }}

    - name: print again
      run: echo done!
