# .github/workflows/postgis_tests.yml

name: test_postressde.py

# Controls when the action will run. Triggers the workflow on push requests to certain files.
on:
  push:
    # Reference: https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths
    paths:
      - 'geopetl/tests/test_postgressde.py'
      - 'geopetl/tests/tests_config.py'
      - 'geopetl/tests/conftest.py'
      - 'geopetl/tests/fixtures_data/**'
      # Trigger on changes to geopetl code-base
      - 'geopetl/**'
      # changes to this workflow file itself.
      - '.github/workflows/postgressde_tests.yml'
      # changes to the geopetl setup.py
      - 'setup.py'
      # changes to postgis-specific docker stuff
      - 'postgressde-docker-compose.yml'
      - 'postgresde_Dockerfile'
      # changes to the docker entrypoint.sh script that runs our pytest commands
      - 'scripts/postgressde_tests_entrypoint.sh'
#    branches:
#      - master
#      - dev-pass
  pull_request:
    branches:
      - master
      - dev-pass


jobs:
  build:
    name: Build and Test Geopetl against an ArcGIS SDE db
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    steps: 

    - name: Checkout the latest github changes
      uses: actions/checkout@v1

    - name: Login to ECR
      uses: docker/login-action@v1
      with:
        registry: 880708401960.dkr.ecr.us-east-1.amazonaws.com/postgresql-sde:latest
        username: ${{ secrets.AWS_ACCESS_KEY_ID}}
        password: ${{ secrets.AWS_SECRET_ACCESS_KEY}}

    - name: Pull down latest postgressde image from ECR
      run: docker pull 880708401960.dkr.ecr.us-east-1.amazonaws.com/postgresql-sde:latest

    - name: Build and bring up the Docker image using docker-compose
      # Abort when any coontainer exits, and return the exit code from geopetl.
      # Otherwise docker-compose won't stop because postgis doesn't exit.
      run: |
        docker-compose -f postgressde-docker-compose.yml up --build --abort-on-container-exit --exit-code-from geopetl
      env:
        POSTGRES_PASSWORD: ${{ secrets.pg_pw }}

# TODO: push image to ECR?
#    - name: Docker Push to ECR (${{ steps.global-vars.outputs.aws_env_prefix }})
#      env: 
#        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        REPOSITORY_URL: 






