# .github/workflows/postgis_tests.yml

name: test_postgis.py

# Controls when the action will run. Triggers the workflow on push requests to certain files.
on:
  push:
    # Reference: https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths
    # Filter reference: https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#filter-pattern-cheat-sheet
    paths:
      # Trigger on changes to geopetl code-base
      - 'geopetl/**'
      # changes to this workflow file itself.
      - '.github/workflows/postgis_tests.yml'
      # changes to the geopetl setup.py
      - 'setup.py'
      # changes to postgis-specific docker stuff
      - 'docker-compose.yml'
      - 'postgis_Dockerfile'
      # changes to the docker entrypoint.sh script that runs our pytest commands
      - 'scripts/entrypoint.sh'



jobs:
  login:
    runs-on: ubuntu-latest
    steps:
      -
        name: Login to ECR
        uses: docker/login-action@v1
        with:
          registry: 880708401960.dkr.ecr.us-east-1.amazonaws.com/postgresql-sde:point-v3
          username: ${{ secrets.AWS_ACCESS_KEY_ID}}
          password: ${{ secrets.AWS_SECRET_ACCESS_KEY}}

      - name: builds 
        run:
          echo "logging in ecr"
          docker ps -a
          echo "docker all containers in ECR"
          docker-compose up --build --abort-on-container-exit --exit-code-from geopetl
          echo "ran docker compose command."


# TODO: push image to ECR?
#    - name: Docker Push to ECR (${{ steps.global-vars.outputs.aws_env_prefix }})
#      env: 
#        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        REPOSITORY_URL: 





