# .github/workflows/postgis_tests.yml

name: test_postgis.py

# Controls when the action will run. Triggers the workflow on push requests to certain files.
on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Build and Test Geopetl against PostGIS db
    # The type of runner that the job will run on
    runs-on: self-hosted
    steps: 

    - name: Checkout the latest github changes
      uses: actions/checkout@v1

    - name: Login to ECR
      uses: docker/login-action@v1
      with:
        registry: 880708401960.dkr.ecr.us-east-1.amazonaws.com/postgresql-sde:latest
        username: ${{ secrets.AWS_ACCESS_KEY_ID}}
        password: ${{ secrets.AWS_SECRET_ACCESS_KEY}}

    - name: Build and bring up the Docker image using docker-compose
      # Abort when any coontainer exits, and return the exit code from geopetl.
      # Otherwise docker-compose won't stop because postgis doesn't exit.
      run: |
        docker-compose -f postgis-docker-compose.yml up --build --abort-on-container-exit --exit-code-from geopetl
      env:
        POSTGRES_PASSWORD: ${{ secrets.pg_pw }}

# TODO: push image to ECR?
#    - name: Docker Push to ECR (${{ steps.global-vars.outputs.aws_env_prefix }})
#      env: 
#        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        REPOSITORY_URL: 






