# .github/workflows/postgis_tests.yml

name: sde_rds_test

# Controls when the action will run. Triggers the workflow on push requests to certain files.
on:
  push:
    # Reference: https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestpaths
    paths:
      - 'geopetl/tests/test_postgis.py'
      - 'geopetl/tests/tests_config.py'
      - 'geopetl/tests/conftest.py'
      - 'geopetl/tests/fixtures_data/**'
      # Trigger on changes to relevant geopetl code-base
      - 'geopetl/postgis.py'
      - 'geopetl/carto.py'
      - 'geopetl/base.py'
      - 'geopetl/__init__.py'
      - 'geopetl/util.py'
      # changes to this workflow file itself.
      - '.github/workflows/sde_rds_tests.yml'
      # changes to the geopetl setup.py
      - 'setup.py'
      # changes to postgis-specific docker stuff
      - 'postgis-sde-rds-docker-compose.yml'
      - 'postgis_sde_rds_Dockerfile'
      # changes to the docker entrypoint.sh script that runs our pytest commands
      - 'scripts/postgis_sde_rds_tests_entrypoint.sh'
#    branches:
#      - master
#      - dev-pass
  pull_request:
    branches:
      - master


jobs:
  build:
    name: Build and Test Geopetl against an ArcGIS SDE db
    # The type of runner that the job will run on
    runs-on: self-hosted
    steps: 

    - name: Checkout the latest github changes
      uses: actions/checkout@v1

    - name: Build and bring up the Docker image using docker-compose
      # Abort when any coontainer exits, and return the exit code from geopetl.
      # Otherwise docker-compose won't stop because postgis doesn't exit.
      run: |
        docker-compose -f postgis-sde-rds-compose.yml up --build --abort-on-container-exit --exit-code-from geopetl

# TODO: push image to ECR?
#    - name: Docker Push to ECR (${{ steps.global-vars.outputs.aws_env_prefix }})
#      env: 
#        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        REPOSITORY_URL: 






