# .github/workflows/sde_rds_tests.yml

name: sde_rds_tests

# Controls when the action will run. Triggers the workflow on push requests to certain files.
on:
  push:
    branches:
      - '**'

jobs:
  build:
    name: Build and Test Geopetl against an ArcGIS RDS SDE database
    # The type of runner that the job will run on
    runs-on: self-hosted
    steps: 

    - name: Checkout the latest github changes
      uses: actions/checkout@v1

    - name: Build and bring up the Docker image using docker-compose
      # Abort when any coontainer exits, and return the exit code from geopetl.
      # Otherwise docker-compose won't stop because postgis doesn't exit.
      run: |
        docker-compose -f sde-rds-compose.yml up --build --abort-on-container-exit --exit-code-from geopetl

# TODO: push image to ECR?
#    - name: Docker Push to ECR (${{ steps.global-vars.outputs.aws_env_prefix }})
#      env: 
#        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
#        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
#        REPOSITORY_URL: 






